import { 
  Hospital, 
  Department, 
  Doctor, 
  DoctorSchedule, 
  Appointment, 
  Queue, 
  MedicalDocument, 
  AppNotification, 
  Profile,
  CareCategory,
  SavedDoctor,
  FamilyMember,
  Prescription,
  DoctorReview,
  HealthTimelineEvent,
  CarePassport
} from '../types';

export const CARE_CATEGORIES: CareCategory[] = [
  {
    id: 'cat-cardio',
    name: 'Cardiology',
    specialty: 'Heart & Vascular Care',
    description: 'Diagnosis and preventive treatment for heart disease, hypertension, palpitations, and rhythm disorders.',
    icon: 'HeartPulse',
    keywords: ['heart', 'cardio', 'blood pressure', 'hypertension', 'palpitation', 'cholesterol', 'chest tightness', 'vascular', 'ecg', 'cardiac', 'dil', 'dil ka dard', 'dil ki bimari', 'seene mein dard', 'high bp', 'heart attack', 'دل'],
    commonSymptoms: ['High blood pressure readings', 'Rapid or fluttering heartbeats', 'Exertional shortness of breath', 'Cardiovascular follow-up']
  },
  {
    id: 'cat-derma',
    name: 'Dermatology',
    specialty: 'Skin, Hair & Nails',
    description: 'Expert care for acne, inflammatory rashes, eczema, psoriasis, hair loss, and clinical skin examinations.',
    icon: 'Sparkles',
    keywords: ['skin', 'rash', 'acne', 'eczema', 'psoriasis', 'mole', 'dermatolog', 'hair loss', 'itch', 'dry skin', 'hives', 'allergy', 'jild', 'daane', 'kharish', 'khujli', 'chehre ke daane', 'baal girna', 'جلد', 'خارش'],
    commonSymptoms: ['Persistent itchy red rashes', 'Severe cystic acne breakouts', 'Unusual mole changes', 'Hair loss & scalp irritation']
  },
  {
    id: 'cat-ortho',
    name: 'Orthopedics',
    specialty: 'Bones, Joints & Spine',
    description: 'Specialized evaluation for back pain, knee and shoulder discomfort, sports injuries, and arthritis.',
    icon: 'Bone',
    keywords: ['back pain', 'bone', 'joint', 'knee', 'shoulder', 'spine', 'fracture', 'ortho', 'ligament', 'arthritis', 'sprain', 'posture', 'hip pain', 'kamar dard', 'kamar ka dard', 'haddi', 'joro ka dard', 'ghutne ka dard', 'pathe ka dard', 'kamar', 'haddi tootna', 'ہڈی', 'کمر درد'],
    commonSymptoms: ['Lower back stiffness & ache', 'Knee swelling after exercise', 'Shoulder mobility pain', 'Arthritic joint discomfort']
  },
  {
    id: 'cat-peds',
    name: 'Pediatrics',
    specialty: 'Children & Adolescents',
    description: 'Comprehensive infant, child, and adolescent healthcare, childhood infections, and growth checkups.',
    icon: 'Baby',
    keywords: ['child', 'pediatric', 'baby', 'infant', 'kid', 'toddler', 'child fever', 'vaccination', 'growth', 'son', 'daughter', 'bacha', 'bache', 'masoom bacha', 'bachon ka doctor', 'tika', 'nawzayedah', 'بچہ', 'بچوں کا ڈاکٹر'],
    commonSymptoms: ['Childhood fever & chills', 'Persistent viral cough in toddlers', 'Routine childhood immunizations', 'Developmental assessments']
  },
  {
    id: 'cat-neuro',
    name: 'Neurology',
    specialty: 'Brain & Nervous System',
    description: 'Clinical evaluation for chronic migraines, peripheral nerve tingling, dizziness, and vestibular balance.',
    icon: 'Brain',
    keywords: ['headache', 'migraine', 'nerve', 'neurolog', 'dizzy', 'tingling', 'numbness', 'tremor', 'seizure', 'memory', 'brain', 'sar dard', 'aadhe sar ka dard', 'chakkar', 'dimagh', 'asab', 'mirgi', 'سر درد', 'دماغ'],
    commonSymptoms: ['Throbbing unilateral migraines', 'Numbness or tingling in extremities', 'Chronic tension headaches', 'Balance and vertigo issues']
  },
  {
    id: 'cat-gyn',
    name: 'Gynecology',
    specialty: "Women's Health",
    description: "Holistic women's reproductive health, hormonal balance, annual pelvic wellness, and preventative screenings.",
    icon: 'UserCheck',
    keywords: ['women', 'gynecolog', 'gynae', 'pelvic', 'period', 'menstrual', 'uterus', 'ovary', 'pcos', 'hormone', 'cramps', 'aurat', 'khawateen', 'haiz', 'mahawari', 'harmone', 'عورت', 'خواتین'],
    commonSymptoms: ['Irregular menstrual cycles', 'PCOS / hormonal concerns', 'Pelvic cramping & discomfort', 'Routine annual wellness checks']
  },
  {
    id: 'cat-obs',
    name: 'Obstetrics',
    specialty: 'Pregnancy & Maternity Care',
    description: 'Antenatal consultations, fetal development ultrasound monitoring, and postpartum maternal care.',
    icon: 'Activity',
    keywords: ['pregnancy', 'pregnant', 'maternity', 'prenatal', 'antenatal', 'baby scan', 'labor', 'trimester', 'fetal', 'obstetric', 'hamal', 'hamila', 'delivery', 'ulaad', 'paidaish', 'حمل'],
    commonSymptoms: ['Prenatal checkups & scans', 'First trimester nausea management', 'Maternal blood pressure tracking', 'Postpartum recovery']
  },
  {
    id: 'cat-ent',
    name: 'ENT (Ear, Nose & Throat)',
    specialty: 'Otolaryngology',
    description: 'Relief for chronic sinusitis, allergic rhinitis, ear infections, tinnitus, and persistent throat discomfort.',
    icon: 'Ear',
    keywords: ['ear', 'nose', 'throat', 'ent', 'sinus', 'tonsil', 'tinnitus', 'hearing', 'hoarse', 'sore throat', 'congestion', 'kaan', 'naak', 'gala', 'kaan ka dard', 'gale mein kharash', 'naak band', 'کان', 'ناک', 'گلا'],
    commonSymptoms: ['Chronic nasal sinus blockage', 'Ringing sensation in ears (tinnitus)', 'Recurrent tonsil inflammation', 'Hoarseness and vocal strain']
  },
  {
    id: 'cat-opht',
    name: 'Ophthalmology',
    specialty: 'Vision & Eye Health',
    description: 'Eye examinations, refractive vision changes, dry eye therapy, diabetic retinal screening, and optical wellness.',
    icon: 'Eye',
    keywords: ['eye', 'vision', 'sight', 'ophthalm', 'blurry', 'cataract', 'glaucoma', 'glasses', 'eye irritation', 'dry eyes', 'aankh', 'aankhon ka doctor', 'nazar', 'dhundla', 'aankh mein jalan', 'motia', 'آنکھ', 'نظر'],
    commonSymptoms: ['Blurry distance or reading vision', 'Excessive eye dryness & strain', 'Flashes or floaters evaluation', 'Routine visual acuity check']
  },
  {
    id: 'cat-dent',
    name: 'Dentistry',
    specialty: 'Dental & Oral Health',
    description: 'Comprehensive dental hygiene, toothache relief, gum health, cavities, and restorative oral care.',
    icon: 'Smile',
    keywords: ['dental', 'dentist', 'tooth', 'teeth', 'toothache', 'gum', 'cavity', 'oral', 'cleaning', 'wisdom tooth', 'crown', 'daant', 'daanton ka doctor', 'masoorhe', 'daant ka dard', 'daanto ka kera', 'دانت'],
    commonSymptoms: ['Sharp sensitivity to cold or hot', 'Throbbing localized toothache', 'Bleeding gums when brushing', 'Routine dental cleaning & scaling']
  },
  {
    id: 'cat-gastro',
    name: 'Gastroenterology',
    specialty: 'Digestive & Liver Health',
    description: 'Care for acid reflux (GERD), chronic abdominal pain, gastritis, IBS, and digestive tract disorders.',
    icon: 'Flame',
    keywords: ['stomach', 'digestion', 'acid', 'reflux', 'heartburn', 'gerd', 'gastro', 'gut', 'constipation', 'diarrhea', 'bloating', 'liver', 'ibs', 'pait dard', 'pait', 'maida', 'tezabiat', 'badhazmi', 'ultee', 'dast', 'gas', 'qabz', 'پیٹ درد', 'معدہ'],
    commonSymptoms: ['Burning chest & acid reflux', 'Frequent bloating after meals', 'Persistent lower abdominal cramps', 'Gastric ulcers & bowel irregularity']
  },
  {
    id: 'cat-pulm',
    name: 'Pulmonology',
    specialty: 'Lungs & Respiratory Care',
    description: 'Management of adult and pediatric asthma, chronic coughing, bronchitis, and post-viral pulmonary recovery.',
    icon: 'Wind',
    keywords: ['cough', 'lung', 'pulmon', 'asthma', 'bronchitis', 'wheezing', 'phlegm', 'chest infection', 'shortness of breath', 'saans', 'dama', 'khansi', 'balgham', 'seene mein jakran', 'saans phoolna', 'پھپھڑے', 'کھانسی', 'دمہ'],
    commonSymptoms: ['Dry persistent tickling cough', 'Wheezing during exertion', 'Seasonal asthma flare-ups', 'Chronic respiratory congestion']
  },
  {
    id: 'cat-uro',
    name: 'Urology',
    specialty: 'Urinary Tract & Men’s Health',
    description: 'Evaluation for kidney stones, urinary tract infections, prostate wellness, and bladder function.',
    icon: 'Droplet',
    keywords: ['urolog', 'urinary', 'kidney stone', 'bladder', 'prostate', 'urine', 'frequent urination', 'burning urination', 'peshab', 'gurday ki pathri', 'masana', 'peshab mein jalan', 'پیشاب'],
    commonSymptoms: ['Painful or frequent urination', 'Flank pain from suspected kidney stones', 'Bladder fullness and discomfort', 'Prostate health screenings']
  },
  {
    id: 'cat-endo',
    name: 'Endocrinology',
    specialty: 'Diabetes & Hormonal Care',
    description: 'Specialized management of Type 1 & 2 diabetes, thyroid nodules, metabolism, and hormonal disorders.',
    icon: 'Zap',
    keywords: ['diabetes', 'sugar', 'thyroid', 'hormone', 'endocrin', 'metabolism', 'insulin', 'weight gain', 'fatigue', 'tsh', 'sugar ki bimari', 'wazan', 'ziabetes', 'ذیابیطس', 'شوگر'],
    commonSymptoms: ['Elevated blood glucose levels', 'Thyroid imbalance (hypo/hyper)', 'Unexplained chronic lethargy', 'Hormonal metabolic fluctuations']
  },
  {
    id: 'cat-psychiatry',
    name: 'Psychiatry',
    specialty: 'Mental Health & Clinical Care',
    description: 'Medical psychiatric evaluation for clinical depression, chronic anxiety, sleep disorders, and mood wellness.',
    icon: 'Smile',
    keywords: ['psychiatr', 'mental health', 'depression', 'anxiety', 'panic', 'insomnia', 'sleep disorder', 'mood', 'bipolar', 'zehni dabao', 'bechaini', 'neend na aana', 'tension', 'afsurdagi', 'ذہنی دباؤ'],
    commonSymptoms: ['Persistent low mood and fatigue', 'Acute panic attacks & anxiety', 'Chronic sleeplessness & insomnia', 'Emotional regulation support']
  },
  {
    id: 'cat-psychology',
    name: 'Psychology',
    specialty: 'Counseling & Psychotherapy',
    description: 'Evidence-based cognitive behavioral therapy, stress management, grief counseling, and behavioral wellness.',
    icon: 'Users',
    keywords: ['psycholog', 'therapy', 'counseling', 'counselor', 'therapist', 'stress', 'burnout', 'grief', 'relationship', 'mashwara', 'zehni sukoon', 'mushawarat'],
    commonSymptoms: ['Workplace burnout & chronic stress', 'Relationship & situational conflict', 'Bereavement and life changes', 'Behavioral coping strategies']
  },
  {
    id: 'cat-onco',
    name: 'Oncology',
    specialty: 'Cancer & Tumor Care',
    description: 'Medical oncology evaluations, preventative screenings, second opinions, and multidisciplinary tumor board care.',
    icon: 'ShieldAlert',
    keywords: ['cancer', 'oncolog', 'tumor', 'chemo', 'biopsy', 'lump', 'malignant', 'screening', 'rasoli', 'giltee', 'کینسر', 'رسولی'],
    commonSymptoms: ['Suspicious persistent lumps', 'Second opinion on biopsy panels', 'Comprehensive tumor screenings', 'Preventive genetic cancer checks']
  },
  {
    id: 'cat-nephro',
    name: 'Nephrology',
    specialty: 'Kidney Health & Dialysis',
    description: 'Care for chronic kidney disease, creatinine elevation, proteinuria, and renal function preservation.',
    icon: 'Activity',
    keywords: ['kidney', 'nephrolog', 'creatinine', 'renal', 'dialysis', 'proteinuria', 'egfr', 'gurday', 'gurday ki bimari', 'گردے'],
    commonSymptoms: ['Elevated serum creatinine tests', 'Foamy urine / proteinuria signs', 'Chronic renal function tracking', 'Fluid retention & leg swelling']
  },
  {
    id: 'cat-genmed',
    name: 'General Medicine',
    specialty: 'Internal Medicine & Primary Care',
    description: 'First-line clinical evaluation, systemic fever, annual executive wellness reviews, and multi-system diagnostics.',
    icon: 'Stethoscope',
    keywords: ['general', 'physician', 'internal medicine', 'fever', 'weakness', 'general checkup', 'body ache', 'unwell', 'routine', 'bukhar', 'thakawat', 'kamzori', 'tabiat kharab', 'jism dard', 'بخار', 'کمزوری'],
    commonSymptoms: ['Unexplained low-grade fevers', 'General fatigue and malaise', 'Comprehensive annual health panel', 'Diagnostic guidance when unsure']
  },
  {
    id: 'cat-fam',
    name: 'Family Medicine',
    specialty: 'Comprehensive Family Care',
    description: 'Continuous, coordinated primary healthcare for all age groups in the family from pediatric to geriatric.',
    icon: 'Home',
    keywords: ['family', 'family medicine', 'general practitioner', 'gp', 'primary care', 'all ages', 'household', 'khandan', 'khandani doctor'],
    commonSymptoms: ['Routine family medical checkups', 'Seasonal influenza reviews', 'Chronic lifestyle disease follow-up', 'Preventative immunizations']
  },
  {
    id: 'cat-physio',
    name: 'Physiotherapy & Rehab',
    specialty: 'Physical Therapy & Recovery',
    description: 'Post-surgical rehabilitation, sports mobility recovery, ergonomic strain correction, and muscle strength restoration.',
    icon: 'ShieldCheck',
    keywords: ['physio', 'physical therapy', 'rehabilitation', 'rehab', 'mobility', 'exercise therapy', 'post surgery', 'strain', 'stiff neck', 'varzish', 'kasrat'],
    commonSymptoms: ['Post-operative joint mobilization', 'Chronic neck & computer strain', 'Sports ligament recovery exercises', 'Spinal alignment therapy']
  },
  {
    id: 'cat-nutri',
    name: 'Nutrition & Dietetics',
    specialty: 'Clinical Nutrition & Diet',
    description: 'Personalized medical dietary plans for diabetes, cardiac health, food sensitivities, and sustainable wellness.',
    icon: 'Apple',
    keywords: ['nutrition', 'diet', 'dietitian', 'nutritionist', 'weight loss', 'cholesterol diet', 'meal plan', 'food allergy', 'parhez', 'ghiza', 'wazan kam karna'],
    commonSymptoms: ['Diabetic nutritional planning', 'Lipid / cholesterol reduction diets', 'Weight management counseling', 'Food intolerance guidance']
  },
  {
    id: 'cat-emergency',
    name: 'Emergency Medicine',
    specialty: '24/7 Acute & Trauma Care',
    description: 'Immediate resuscitation, acute surgical triage, and critical stabilization for life-threatening medical emergencies.',
    icon: 'AlertTriangle',
    keywords: ['emergency', 'trauma', 'er', 'critical', 'acute', 'urgent', 'ambulance', '911', 'accident', 'shadeed dard', 'behosh', 'fori', 'ایمرجنسی', 'فوری'],
    commonSymptoms: ['Severe chest crushing pain', 'Sudden loss of consciousness', 'Severe respiratory failure', 'Uncontrolled acute hemorrhage']
  }
];

// ==============================================================================
// 2. 5 REGIONAL DEMO HOSPITALS (Curated high-res medical imagery with fallbacks)
// ==============================================================================
export const INITIAL_HOSPITALS: Hospital[] = [
  {
    id: 'hosp-shifa-isb',
    name: 'Shifa International Hospital',
    address: 'Sector H-8/4, Pitras Bukhari Road',
    city: 'Islamabad',
    phone: '+92 (51) 846-3000',
    emergency_phone: '+92 (51) 846-3111',
    opening_hours: 'Open 24/7 • Specialized Clinics 08:00 AM - 08:00 PM',
    description: 'Leading JCI-accredited tertiary care university medical center in the federal capital, featuring comprehensive cardiology, liver transplant, oncology, neurology, and pediatrics.',
    hero_image: 'https://images.unsplash.com/photo-1587351021759-3e566b6af7cc?w=1200&auto=format&fit=crop&q=80',
    thumbnail_image: 'https://images.unsplash.com/photo-1519494026892-80bbd2d6fd0d?w=600&auto=format&fit=crop&q=80',
    facilities: ['24/7 Level-1 Emergency & Trauma', 'Liver & Kidney Transplant Center', 'Coronary Care Unit (CCU)', 'Advanced Robotic Surgery', 'Dedicated Pediatric Wing'],
    is_active: true,
    is_reference_network: true,
    availability_status: 'AVAILABLE',
    google_maps_url: 'https://maps.google.com/?q=Shifa+International+Hospital+Islamabad',
    doctor_count: 24,
    next_available_slot: 'Today, 02:00 PM',
  },
  {
    id: 'hosp-skmch-lhr',
    name: 'Shaukat Khanum Memorial Cancer Hospital',
    address: '7A, Block R-3, Johar Town',
    city: 'Lahore',
    phone: '+92 (42) 3590-5000',
    emergency_phone: '+92 (42) 3590-5111',
    opening_hours: 'Open 24/7 Continuous Emergency • Outpatient 08:30 AM - 05:00 PM',
    description: 'Pioneering specialized oncology and clinical research institution providing state-of-the-art radiation therapy, surgical oncology, nuclear medicine, and clinical neurology.',
    hero_image: 'https://images.unsplash.com/photo-1519494026892-80bbd2d6fd0d?w=1200&auto=format&fit=crop&q=80',
    thumbnail_image: 'https://images.unsplash.com/photo-1519494026892-80bbd2d6fd0d?w=600&auto=format&fit=crop&q=80',
    facilities: ['PET-CT & Molecular Imaging', 'Linear Accelerator Radiotherapy', 'Bone Marrow Transplant', 'Specialized Neuro-Oncology', 'Central Clinical Lab'],
    is_active: true,
    is_reference_network: true,
    availability_status: 'AVAILABLE',
    google_maps_url: 'https://maps.google.com/?q=Shaukat+Khanum+Memorial+Cancer+Hospital+Lahore',
    doctor_count: 18,
    next_available_slot: 'Tomorrow, 10:30 AM',
  },
  {
    id: 'hosp-akuh-khi',
    name: 'Aga Khan University Hospital',
    address: 'National Stadium Road',
    city: 'Karachi',
    phone: '+92 (21) 111-911-911',
    emergency_phone: '+92 (21) 3486-1111',
    opening_hours: 'Open 24/7 Emergency & Inpatient Services',
    description: 'Premier international academic medical center with internationally certified clinical specialties, world-class cardiology, neurology, pediatrics, and emergency trauma resuscitation.',
    hero_image: 'https://images.unsplash.com/photo-1586773860418-d37222d8fce3?w=1200&auto=format&fit=crop&q=80',
    thumbnail_image: 'https://images.unsplash.com/photo-1586773860418-d37222d8fce3?w=600&auto=format&fit=crop&q=80',
    facilities: ['JCI Gold Seal Accreditation', 'Level-1 Trauma Emergency', 'State-of-the-Art Heart Center', 'Maternal & Fetal Medicine', 'Comprehensive Dialysis Center'],
    is_active: true,
    is_reference_network: true,
    availability_status: 'AVAILABLE',
    google_maps_url: 'https://maps.google.com/?q=Aga+Khan+University+Hospital+Karachi',
    doctor_count: 32,
    next_available_slot: 'Today, 03:30 PM',
  },
  {
    id: 'hosp-pic-lhr',
    name: 'Punjab Institute of Cardiology (PIC)',
    address: 'Ghaus-ul-Azam Road / Jail Road, Shadman',
    city: 'Lahore',
    phone: '+92 (42) 9920-3051',
    emergency_phone: '+92 (42) 9920-3060',
    opening_hours: 'Open 24/7 Acute Cardiac Emergency',
    description: 'Apex cardiovascular hospital of Punjab providing emergency primary PCI angioplasty, adult & pediatric cardiac surgery, echocardiography, and vascular intervention.',
    hero_image: 'https://images.unsplash.com/photo-1629909613654-28e377c37b09?w=1200&auto=format&fit=crop&q=80',
    thumbnail_image: 'https://images.unsplash.com/photo-1629909613654-28e377c37b09?w=600&auto=format&fit=crop&q=80',
    facilities: ['24/7 Emergency Angioplasty (Primary PCI)', '6 Cardiac Catheterization Labs', 'Pediatric Cardiac Surgery Center', 'Coronary ICU', 'Cardiac Rehab'],
    is_active: true,
    is_reference_network: true,
    availability_status: 'AVAILABLE',
    google_maps_url: 'https://maps.google.com/?q=Punjab+Institute+of+Cardiology+Lahore',
    doctor_count: 22,
    next_available_slot: 'Today, 11:30 AM',
  },
  {
    id: 'hosp-services-lhr',
    name: 'Services Hospital',
    address: 'Ghaus-ul-Azam Road, Shadman',
    city: 'Lahore',
    phone: '+92 (42) 9920-3402',
    emergency_phone: '+92 (42) 9920-3420',
    opening_hours: 'Open 24/7 Emergency • Outpatient 08:00 AM - 02:00 PM',
    description: 'Major public teaching hospital affiliated with SIMS, housing renowned departments in dermatology, endocrinology, gastroenterology, general surgery, and gynecology.',
    hero_image: 'https://images.unsplash.com/photo-1538108149393-fbbd81895907?w=1200&auto=format&fit=crop&q=80',
    thumbnail_image: 'https://images.unsplash.com/photo-1538108149393-fbbd81895907?w=600&auto=format&fit=crop&q=80',
    facilities: ['Regional Dermatology Center', 'Endocrinology & Diabetes Clinic', 'Surgical Emergency', 'Endoscopy Unit', 'Blood Bank'],
    is_active: true,
    is_reference_network: true,
    availability_status: 'AVAILABLE',
    google_maps_url: 'https://maps.google.com/?q=Services+Hospital+Lahore',
    doctor_count: 20,
    next_available_slot: 'Tomorrow, 09:00 AM',
  },
  {
    id: 'hosp-mayo-lhr',
    name: 'Mayo Hospital',
    address: 'Hospital Road, Anarkali',
    city: 'Lahore',
    phone: '+92 (42) 9921-1100',
    emergency_phone: '+92 (42) 9921-1122',
    opening_hours: 'Open 24/7 Continuous Emergency Triage',
    description: 'Historic apex hospital in South Asia affiliated with King Edward Medical University, featuring a massive emergency block, pediatric medicine, ophthalmology, and ENT.',
    hero_image: 'https://images.unsplash.com/photo-1516549655169-df83a0774514?w=1200&auto=format&fit=crop&q=80',
    thumbnail_image: 'https://images.unsplash.com/photo-1516549655169-df83a0774514?w=600&auto=format&fit=crop&q=80',
    facilities: ['New Emergency Department (Tower)', 'Ophthalmology Institute', 'Pediatric Intensive Care Unit', 'Trauma Resuscitation Center', 'Audiology Center'],
    is_active: true,
    is_reference_network: true,
    availability_status: 'AVAILABLE',
    google_maps_url: 'https://maps.google.com/?q=Mayo+Hospital+Lahore',
    doctor_count: 28,
    next_available_slot: 'Today, 01:00 PM',
  },
  {
    id: 'hosp-pims-isb',
    name: 'Pakistan Institute of Medical Sciences (PIMS)',
    address: 'Sector G-8/3',
    city: 'Islamabad',
    phone: '+92 (51) 926-1170',
    emergency_phone: '+92 (51) 926-1180',
    opening_hours: 'Open 24/7 Emergency & Specialized OPD',
    description: 'Premier national institute in Islamabad featuring the Children Hospital, Mother and Child Health Centre (MCH), burn center, and full multi-specialty outpatient clinics.',
    hero_image: 'https://images.unsplash.com/photo-1584515979956-d9f6e5d09982?w=1200&auto=format&fit=crop&q=80',
    thumbnail_image: 'https://images.unsplash.com/photo-1584515979956-d9f6e5d09982?w=600&auto=format&fit=crop&q=80',
    facilities: ['Children Hospital Institute', 'Burn Care & Reconstruction Center', 'Mother & Child Health (MCH)', 'Level-1 Emergency Wing', 'Nephrology & Hemodialysis'],
    is_active: true,
    is_reference_network: true,
    availability_status: 'AVAILABLE',
    google_maps_url: 'https://maps.google.com/?q=PIMS+Hospital+Islamabad',
    doctor_count: 26,
    next_available_slot: 'Tomorrow, 09:30 AM',
  },
  {
    id: 'hosp-cmh-lhr',
    name: 'Combined Military Hospital (CMH)',
    address: 'Abid Majeed Road, Lahore Cantt',
    city: 'Lahore',
    phone: '+92 (42) 3669-3000',
    emergency_phone: '+92 (42) 3669-3111',
    opening_hours: 'Open 24/7 Acute Trauma & General Healthcare',
    description: 'Advanced tertiary care military and civilian hospital with premier joint replacement, spine surgery, orthopedic sports trauma, reconstructive surgery, and intensive care.',
    hero_image: 'https://images.unsplash.com/photo-1505751172876-fa1923c5c528?w=1200&auto=format&fit=crop&q=80',
    thumbnail_image: 'https://images.unsplash.com/photo-1505751172876-fa1923c5c528?w=600&auto=format&fit=crop&q=80',
    facilities: ['Center for Advanced Orthopedics & Spine', 'Trauma Resuscitation Unit', 'Specialized Burns Unit', 'MRI & CT Diagnostic Suite', 'Physical Rehab Center'],
    is_active: true,
    is_reference_network: true,
    availability_status: 'AVAILABLE',
    google_maps_url: 'https://maps.google.com/?q=CMH+Lahore',
    doctor_count: 25,
    next_available_slot: 'Tomorrow, 11:00 AM',
  },
  {
    id: 'hosp-ric-rwp',
    name: 'Rawalpindi Institute of Cardiology (RIC)',
    address: 'Rawal Road, Rawalpindi',
    city: 'Rawalpindi',
    phone: '+92 (51) 928-1111',
    emergency_phone: '+92 (51) 928-1122',
    opening_hours: 'Open 24/7 Acute Cardiac Emergency',
    description: 'Specialized apex cardiovascular center in Rawalpindi-Islamabad providing round-the-clock emergency angioplasty, cardiac surgery, ICU facilities, and pediatric cardiology.',
    hero_image: 'https://images.unsplash.com/photo-1512678080530-7760d81faba6?w=1200&auto=format&fit=crop&q=80',
    thumbnail_image: 'https://images.unsplash.com/photo-1512678080530-7760d81faba6?w=600&auto=format&fit=crop&q=80',
    facilities: ['24/7 Primary PCI (Angioplasty)', 'Coronary Care Unit (CCU)', 'Open Heart Surgery Theatres', 'Pediatric Cardiology', 'Emergency Cardiac Ambulance'],
    is_active: true,
    is_reference_network: true,
    availability_status: 'AVAILABLE',
    google_maps_url: 'https://maps.google.com/?q=Rawalpindi+Institute+of+Cardiology',
    doctor_count: 24,
    next_available_slot: 'Today, 04:30 PM',
  }
];

// ==============================================================================
// 3. DEPARTMENTS LINKED TO PAKISTANI HOSPITALS
// ==============================================================================
export const INITIAL_DEPARTMENTS: Department[] = [
  // Shifa International Hospital (Islamabad)
  { id: 'd-shifa-cardio', hospital_id: 'hosp-shifa-isb', name: 'Cardiology', specialty: 'Heart & Vascular', description: 'Interventional cardiology, echocardiography, hypertension, and electrophysiology.', icon: 'HeartPulse', is_active: true, hospital: INITIAL_HOSPITALS[0] },
  { id: 'd-shifa-ortho', hospital_id: 'hosp-shifa-isb', name: 'Orthopedics', specialty: 'Bones & Spine', description: 'Total joint replacements, complex spine surgery, and sports medicine.', icon: 'Bone', is_active: true, hospital: INITIAL_HOSPITALS[0] },
  { id: 'd-shifa-peds', hospital_id: 'hosp-shifa-isb', name: 'Pediatrics', specialty: 'Child Healthcare', description: 'Comprehensive infant care, childhood fever, and developmental checks.', icon: 'Baby', is_active: true, hospital: INITIAL_HOSPITALS[0] },
  { id: 'd-shifa-neuro', hospital_id: 'hosp-shifa-isb', name: 'Neurology', specialty: 'Brain & Nerves', description: 'Comprehensive stroke care, migraine clinics, and epilepsy management.', icon: 'Brain', is_active: true, hospital: INITIAL_HOSPITALS[0] },

  // Shaukat Khanum (Lahore)
  { id: 'd-skmch-onco', hospital_id: 'hosp-skmch-lhr', name: 'Oncology', specialty: 'Cancer Care', description: 'Medical and surgical oncology, radiation therapy, and specialized tumor boards.', icon: 'ShieldAlert', is_active: true, hospital: INITIAL_HOSPITALS[1] },
  { id: 'd-skmch-neuro', hospital_id: 'hosp-skmch-lhr', name: 'Neurology', specialty: 'Brain & Nervous System', description: 'Neuro-oncology and clinical neurological diagnostic assessments.', icon: 'Brain', is_active: true, hospital: INITIAL_HOSPITALS[1] },
  { id: 'd-skmch-gen', hospital_id: 'hosp-skmch-lhr', name: 'General Medicine', specialty: 'Internal Medicine', description: 'Primary triage, preventive health panels, and systemic examinations.', icon: 'Stethoscope', is_active: true, hospital: INITIAL_HOSPITALS[1] },

  // Aga Khan University Hospital (Karachi)
  { id: 'd-akuh-cardio', hospital_id: 'hosp-akuh-khi', name: 'Cardiology', specialty: 'Cardiovascular Sciences', description: 'Advanced catheterization, coronary artery disease, and rhythm therapy.', icon: 'HeartPulse', is_active: true, hospital: INITIAL_HOSPITALS[2] },
  { id: 'd-akuh-derma', hospital_id: 'hosp-akuh-khi', name: 'Dermatology', specialty: 'Skin & Aesthetics', description: 'Complex dermatological therapeutics, eczema, and dermatosurgery.', icon: 'Sparkles', is_active: true, hospital: INITIAL_HOSPITALS[2] },
  { id: 'd-akuh-pulm', hospital_id: 'hosp-akuh-khi', name: 'Pulmonology', specialty: 'Lungs & Respiration', description: 'Asthma therapeutics, chronic bronchitis, and critical care pulmonary medicine.', icon: 'Wind', is_active: true, hospital: INITIAL_HOSPITALS[2] },
  { id: 'd-akuh-peds', hospital_id: 'hosp-akuh-khi', name: 'Pediatrics', specialty: 'Child Healthcare', description: 'Neonatology, pediatric critical care, and child growth assessments.', icon: 'Baby', is_active: true, hospital: INITIAL_HOSPITALS[2] },

  // Punjab Institute of Cardiology (Lahore)
  { id: 'd-pic-cardio', hospital_id: 'hosp-pic-lhr', name: 'Cardiology', specialty: 'Heart & Vascular', description: '24/7 Primary PCI angioplasty, heart failure, and coronary interventions.', icon: 'HeartPulse', is_active: true, hospital: INITIAL_HOSPITALS[3] },
  { id: 'd-pic-cardiac-surg', hospital_id: 'hosp-pic-lhr', name: 'Emergency Medicine', specialty: 'Acute Cardiac Resuscitation', description: 'Acute coronary syndrome emergency stabilization and CCU triage.', icon: 'AlertTriangle', is_active: true, hospital: INITIAL_HOSPITALS[3] },

  // Services Hospital (Lahore)
  { id: 'd-services-derma', hospital_id: 'hosp-services-lhr', name: 'Dermatology', specialty: 'Skin, Hair & Nails', description: 'Premier dermatology department for severe acne, rashes, and psoriasis.', icon: 'Sparkles', is_active: true, hospital: INITIAL_HOSPITALS[4] },
  { id: 'd-services-gyn', hospital_id: 'hosp-services-lhr', name: 'Gynecology', specialty: "Women's Health", description: "Maternal pelvic wellness, PCOS management, and antenatal clinics.", icon: 'UserCheck', is_active: true, hospital: INITIAL_HOSPITALS[4] },
  { id: 'd-services-gastro', hospital_id: 'hosp-services-lhr', name: 'Gastroenterology', specialty: 'Digestive Health', description: 'Endoscopy, GERD acid reflux, and inflammatory bowel care.', icon: 'Flame', is_active: true, hospital: INITIAL_HOSPITALS[4] },

  // Mayo Hospital (Lahore)
  { id: 'd-mayo-peds', hospital_id: 'hosp-mayo-lhr', name: 'Pediatrics', specialty: 'Pediatric Medicine', description: 'Infant emergency, childhood immunization, and pediatric infections.', icon: 'Baby', is_active: true, hospital: INITIAL_HOSPITALS[5] },
  { id: 'd-mayo-ent', hospital_id: 'hosp-mayo-lhr', name: 'ENT (Ear, Nose & Throat)', specialty: 'Otolaryngology', description: 'Sinus surgery, ear microsurgery, and audio-vestibular testing.', icon: 'Ear', is_active: true, hospital: INITIAL_HOSPITALS[5] },
  { id: 'd-mayo-opht', hospital_id: 'hosp-mayo-lhr', name: 'Ophthalmology', specialty: 'Eye Care', description: 'Retinal surgery, visual acuity diagnostics, and cataract therapy.', icon: 'Eye', is_active: true, hospital: INITIAL_HOSPITALS[5] },

  // PIMS (Islamabad)
  { id: 'd-pims-peds', hospital_id: 'hosp-pims-isb', name: 'Pediatrics', specialty: 'Children Hospital Institute', description: 'National apex children hospital, pediatric neonatal care, and vaccines.', icon: 'Baby', is_active: true, hospital: INITIAL_HOSPITALS[6] },
  { id: 'd-pims-gyn', hospital_id: 'hosp-pims-isb', name: 'Gynecology', specialty: 'MCH Center', description: 'Mother & Child Health, high-risk obstetrics, and pelvic care.', icon: 'UserCheck', is_active: true, hospital: INITIAL_HOSPITALS[6] },
  { id: 'd-pims-dent', hospital_id: 'hosp-pims-isb', name: 'Dentistry', specialty: 'Oral Surgery & Health', description: 'Dental restorations, maxillofacial triage, and routine oral hygiene.', icon: 'Smile', is_active: true, hospital: INITIAL_HOSPITALS[6] },

  // CMH (Lahore)
  { id: 'd-cmh-ortho', hospital_id: 'hosp-cmh-lhr', name: 'Orthopedics', specialty: 'Bones, Joints & Spine', description: 'Premier joint replacement center, back pain clinic, and sports trauma.', icon: 'Bone', is_active: true, hospital: INITIAL_HOSPITALS[7] },
  { id: 'd-cmh-physio', hospital_id: 'hosp-cmh-lhr', name: 'Physiotherapy & Rehab', specialty: 'Physical Rehabilitation', description: 'Post-operative mobilization, spine conditioning, and ergonomic therapy.', icon: 'ShieldCheck', is_active: true, hospital: INITIAL_HOSPITALS[7] },
  { id: 'd-cmh-trauma', hospital_id: 'hosp-cmh-lhr', name: 'Emergency Medicine', specialty: 'Acute Trauma Care', description: 'Level-1 acute surgical resuscitation and 24/7 trauma triage.', icon: 'AlertTriangle', is_active: true, hospital: INITIAL_HOSPITALS[7] },

  // Rawalpindi Institute of Cardiology (Rawalpindi)
  { id: 'd-ric-cardio', hospital_id: 'hosp-ric-rwp', name: 'Cardiology', specialty: 'Heart & Vascular', description: 'Emergency primary PCI angioplasty, coronary intensive care, and rhythm treatment.', icon: 'HeartPulse', is_active: true, hospital: INITIAL_HOSPITALS[8] },
  { id: 'd-ric-surg', hospital_id: 'hosp-ric-rwp', name: 'Cardiothoracic Surgery', specialty: 'Heart Surgery', description: 'Advanced bypass surgeries, pediatric heart interventions, and valve reconstructions.', icon: 'Activity', is_active: true, hospital: INITIAL_HOSPITALS[8] },

  // Legacy mappings for tests
  { id: 'd-lahore1-cardio', hospital_id: 'hosp-skmch-lhr', name: 'Cardiology', specialty: 'Heart & Vascular', description: 'Cardiovascular care.', icon: 'HeartPulse', is_active: true, hospital: INITIAL_HOSPITALS[1] },
  { id: 'd-lahore1-derma', hospital_id: 'hosp-skmch-lhr', name: 'Dermatology', specialty: 'Skin & Acne Care', description: 'Acne therapy.', icon: 'Sparkles', is_active: true, hospital: INITIAL_HOSPITALS[1] },
  { id: 'd-lahore1-ortho', hospital_id: 'hosp-skmch-lhr', name: 'Orthopedics', specialty: 'Bones & Spine', description: 'Spinal discomfort.', icon: 'Bone', is_active: true, hospital: INITIAL_HOSPITALS[1] },
  { id: 'd-lahore1-peds', hospital_id: 'hosp-skmch-lhr', name: 'Pediatrics', specialty: 'Child Healthcare', description: 'Infant care.', icon: 'Baby', is_active: true, hospital: INITIAL_HOSPITALS[1] },
  { id: 'd-lahore1-neuro', hospital_id: 'hosp-skmch-lhr', name: 'Neurology', specialty: 'Brain & Nerves', description: 'Migraine clinic.', icon: 'Brain', is_active: true, hospital: INITIAL_HOSPITALS[1] },
  { id: 'd-lahore2-ortho', hospital_id: 'hosp-pic-lhr', name: 'Orthopedics', specialty: 'Joints & Spine Care', description: 'Complex back pain.', icon: 'Bone', is_active: true, hospital: INITIAL_HOSPITALS[3] },
  { id: 'd-isb-peds', hospital_id: 'hosp-shifa-isb', name: 'Pediatrics', specialty: 'Child & Adolescent Care', description: 'Infant health.', icon: 'Baby', is_active: true, hospital: INITIAL_HOSPITALS[0] },
  { id: 'd-rwp-opht', hospital_id: 'hosp-pims-isb', name: 'Ophthalmology', specialty: 'Eye Care & Microsurgery', description: 'Visual acuity.', icon: 'Eye', is_active: true, hospital: INITIAL_HOSPITALS[6] },
  { id: 'd-khi-pulm', hospital_id: 'hosp-akuh-khi', name: 'Pulmonology', specialty: 'Lungs & Respiration', description: 'Asthma treatments.', icon: 'Wind', is_active: true, hospital: INITIAL_HOSPITALS[2] },
];

// ==============================================================================
// 4. DEMO PROFILES FOR 1-CLICK AUTH
// ==============================================================================
export const DEMO_PROFILES: Record<string, Profile> = {
  patient: {
    id: 'c0000000-0000-0000-0000-000000000001',
    role: 'patient',
    full_name: 'Ahmed Khan',
    email: 'patient.ahmed@careflow.ai',
    phone: '+92 (300) 900-0001',
    avatar_url: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&auto=format&fit=crop&q=80',
  },
  doctor: {
    id: 'b0000000-0000-0000-0000-000000000001',
    role: 'doctor',
    full_name: 'Dr. Sarah Farooq, FCPS',
    email: 'dr.sarah.farooq@careflow.ai',
    phone: '+92 (300) 100-0001',
    avatar_url: 'https://images.unsplash.com/photo-1559839734-2b71ea197ec2?w=150&auto=format&fit=crop&q=80',
  },
  admin: {
    id: 'a0000000-0000-0000-0000-000000000001',
    role: 'admin',
    full_name: 'Hospital Administrator',
    email: 'admin@careflow.ai',
    phone: '+92 (300) 000-0001',
    avatar_url: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&auto=format&fit=crop&q=80',
  }
};

// ==============================================================================
// 5. 20+ VERIFIED SPECIALISTS ACROSS ALL 5 HOSPITALS
// ==============================================================================
export const INITIAL_DOCTORS: Doctor[] = [
  // Punjab Institute of Cardiology & Shifa
  {
    id: 'doc-cardio-1',
    profile_id: 'b0000000-0000-0000-0000-000000000001',
    hospital_id: 'hosp-pic-lhr',
    specialty: 'Cardiology',
    bio: 'Senior Consultant Interventional Cardiologist specializing in preventive heart disease, primary PCI angioplasty, and hypertension management.',
    experience_years: 16,
    consultation_fee: 180,
    consultation_fee_pkr: 3000,
    available_days: ['Monday', 'Tuesday', 'Thursday', 'Friday'],
    is_active: true,
    is_approved: true,
    is_demo_profile: true,
    rating: 4.9,
    review_count: 142,
    languages: ['English', 'Urdu', 'Punjabi'],
    education: 'MBBS (KE), FCPS (Cardiology), MRCP (UK)',
    qualifications: 'MBBS, FCPS (Cardiology), Fellowship Interventional Cardiology',
    next_available_slot: 'Today, 02:30 PM',
    profile: {
      id: 'b0000000-0000-0000-0000-000000000001',
      role: 'doctor',
      full_name: 'Dr. Ahmed Raza, FCPS',
      email: 'dr.sarah.jenkins@careflow.ai',
      avatar_url: 'https://images.unsplash.com/photo-1622253692010-333f2da6031d?w=150&auto=format&fit=crop&q=80',
    },
    hospital: INITIAL_HOSPITALS[3],
  },
  {
    id: 'doc-derma-1',
    profile_id: null,
    hospital_id: 'hosp-services-lhr',
    specialty: 'Dermatology',
    bio: 'Specialist Dermatologist focused on severe acne protocols, allergic dermatitis, and diagnostic dermoscopy.',
    experience_years: 12,
    consultation_fee: 150,
    consultation_fee_pkr: 2500,
    available_days: ['Monday', 'Wednesday', 'Friday', 'Saturday'],
    is_active: true,
    is_approved: true,
    is_demo_profile: true,
    rating: 4.9,
    review_count: 98,
    languages: ['English', 'Urdu'],
    education: 'MBBS (SIMS), MD (Dermatology), Member BAD',
    qualifications: 'MBBS, MD Dermatology, Clinical Dermoscopy Certified',
    next_available_slot: 'Tomorrow, 10:00 AM',
    profile: {
      id: 'p-doc-ayesha',
      role: 'doctor',
      full_name: 'Dr. Ayesha Khan, MD',
      email: 'dr.ayesha.khan@careflow.ai',
      avatar_url: 'https://images.unsplash.com/photo-1594824813684-25e6ffc6b541?w=150&auto=format&fit=crop&q=80',
    },
    hospital: INITIAL_HOSPITALS[4],
  },
  {
    id: 'doc-ortho-1',
    profile_id: null,
    hospital_id: 'hosp-cmh-lhr',
    specialty: 'Orthopedics',
    bio: 'Orthopedic and spine surgeon focusing on spinal disc health, lower back pain rehabilitation, and knee arthroscopy.',
    experience_years: 17,
    consultation_fee: 200,
    consultation_fee_pkr: 3500,
    available_days: ['Tuesday', 'Wednesday', 'Thursday'],
    is_active: true,
    is_approved: true,
    is_demo_profile: true,
    rating: 4.9,
    review_count: 124,
    languages: ['English', 'Urdu', 'Punjabi'],
    education: 'MBBS (AIMC), FRCS (Tr & Orth), Fellowship in Spine Surgery',
    qualifications: 'MBBS, FRCS (Orthopedics), AO Spine Fellow',
    next_available_slot: 'Tomorrow, 01:30 PM',
    profile: {
      id: 'p-doc-hamza',
      role: 'doctor',
      full_name: 'Dr. Hamza Malik, FRCS',
      email: 'dr.hamza.malik@careflow.ai',
      avatar_url: 'https://images.unsplash.com/photo-1582750433449-648ed127bb54?w=150&auto=format&fit=crop&q=80',
    },
    hospital: INITIAL_HOSPITALS[7],
  },
  {
    id: 'doc-ortho-shifa',
    profile_id: null,
    hospital_id: 'hosp-shifa-isb',
    specialty: 'Orthopedics',
    bio: 'Chief Consultant Orthopedic & Spine Surgeon specializing in disc disorders, lumbar spine arthroplasty, and musculoskeletal trauma.',
    experience_years: 19,
    consultation_fee: 220,
    consultation_fee_pkr: 3500,
    available_days: ['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday'],
    is_active: true,
    is_approved: true,
    is_demo_profile: true,
    rating: 4.9,
    review_count: 156,
    languages: ['English', 'Urdu'],
    education: 'MBBS (KE), FRCS (Tr & Orth), FACS',
    qualifications: 'MBBS, FRCS Orthopedic Surgery, Fellow American College of Surgeons',
    next_available_slot: 'Today, 03:00 PM',
    profile: {
      id: 'p-doc-bilal-shifa',
      role: 'doctor',
      full_name: 'Dr. Bilal Tariq, FRCS',
      email: 'dr.bilal.tariq@careflow.ai',
      avatar_url: 'https://images.unsplash.com/photo-1622253692010-333f2da6031d?w=150&auto=format&fit=crop&q=80',
    },
    hospital: INITIAL_HOSPITALS[0],
  },
  {
    id: 'doc-peds-1',
    profile_id: null,
    hospital_id: 'hosp-pims-isb',
    specialty: 'Pediatrics',
    bio: 'Dedicated pediatrician providing comprehensive infant wellness, fever care, and childhood immunization at Children Hospital Institute.',
    experience_years: 11,
    consultation_fee: 130,
    consultation_fee_pkr: 2200,
    available_days: ['Monday', 'Tuesday', 'Wednesday', 'Friday'],
    is_active: true,
    is_approved: true,
    is_demo_profile: true,
    rating: 4.9,
    review_count: 108,
    languages: ['English', 'Urdu', 'Pashto'],
    education: 'MBBS (RMC), FCPS (Pediatrics), DCH',
    qualifications: 'MBBS, FCPS Pediatrics, Pediatric Resuscitation Certified',
    next_available_slot: 'Today, 03:00 PM',
    profile: {
      id: 'p-doc-fatima-noor',
      role: 'doctor',
      full_name: 'Dr. Fatima Noor, FCPS',
      email: 'dr.fatima.noor@careflow.ai',
      avatar_url: 'https://images.unsplash.com/photo-1559839734-2b71ea197ec2?w=150&auto=format&fit=crop&q=80',
    },
    hospital: INITIAL_HOSPITALS[6],
  },
  {
    id: 'doc-ortho-2',
    profile_id: null,
    hospital_id: 'hosp-cmh-lhr',
    specialty: 'Orthopedics',
    bio: 'Senior spine and orthopedic consultant with clinical focus on complex lower back pain, sciatica, and joint restoration.',
    experience_years: 18,
    consultation_fee: 220,
    consultation_fee_pkr: 3500,
    available_days: ['Monday', 'Tuesday', 'Wednesday', 'Thursday'],
    is_active: true,
    is_approved: true,
    is_demo_profile: true,
    rating: 4.9,
    review_count: 160,
    languages: ['English', 'Urdu', 'Punjabi'],
    education: 'MBBS (KE), FRCS (Glasg), MCh Orth',
    qualifications: 'MBBS, FRCS (Tr & Orth), Master of Orthopedic Surgery',
    next_available_slot: 'Tomorrow, 11:00 AM',
    profile: {
      id: 'p-doc-tariq',
      role: 'doctor',
      full_name: 'Dr. Tariq Mehmood, FRCS',
      email: 'dr.tariq.mehmood@careflow.ai',
      avatar_url: 'https://images.unsplash.com/photo-1537368910025-700350fe46c7?w=150&auto=format&fit=crop&q=80',
    },
    hospital: INITIAL_HOSPITALS[7],
  },
  {
    id: 'doc-neuro-1',
    profile_id: null,
    hospital_id: 'hosp-skmch-lhr',
    specialty: 'Neurology',
    bio: 'Senior Neurologist specializing in persistent migraine syndromes, nerve conduction studies, and tremor management.',
    experience_years: 15,
    consultation_fee: 210,
    consultation_fee_pkr: 3200,
    available_days: ['Wednesday', 'Thursday', 'Friday'],
    is_active: true,
    is_approved: true,
    is_demo_profile: true,
    rating: 4.8,
    review_count: 86,
    languages: ['English', 'Urdu'],
    education: 'MBBS (KE), MRCP (UK), Specialty Certificate in Neurology',
    qualifications: 'MBBS, MRCP Neurology (London)',
    next_available_slot: 'Thursday, 02:00 PM',
    profile: {
      id: 'p-doc-usman',
      role: 'doctor',
      full_name: 'Dr. Usman Ali, MRCP',
      email: 'dr.usman.ali@careflow.ai',
      avatar_url: 'https://images.unsplash.com/photo-1612349317150-e413f6a5b16d?w=150&auto=format&fit=crop&q=80',
    },
    hospital: INITIAL_HOSPITALS[1],
  },
  {
    id: 'doc-physio-1',
    profile_id: null,
    hospital_id: 'hosp-cmh-lhr',
    specialty: 'Physiotherapy / Rehabilitation',
    bio: 'Lead rehabilitation physiotherapist addressing back stiffness, sports muscle strain, and post-surgery mobility.',
    experience_years: 12,
    consultation_fee: 100,
    consultation_fee_pkr: 1800,
    available_days: ['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday'],
    is_active: true,
    is_approved: true,
    is_demo_profile: true,
    rating: 4.8,
    review_count: 64,
    languages: ['English', 'Urdu'],
    education: 'DPT, MS OMPT',
    qualifications: 'Doctor of Physical Therapy, Orthopedic Manual Physical Therapy',
    next_available_slot: 'Today, 04:00 PM',
    profile: {
      id: 'p-doc-zainab',
      role: 'doctor',
      full_name: 'Dr. Zainab Qureshi, DPT',
      email: 'dr.zainab.qureshi@careflow.ai',
      avatar_url: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=150&auto=format&fit=crop&q=80',
    },
    hospital: INITIAL_HOSPITALS[7],
  },
  {
    id: 'doc-gyn-1',
    profile_id: null,
    hospital_id: 'hosp-services-lhr',
    specialty: 'Gynecology',
    bio: "Senior gynecologist providing specialized care in hormonal balance, PCOS diagnostics, and preventative reproductive health.",
    experience_years: 14,
    consultation_fee: 190,
    consultation_fee_pkr: 2800,
    available_days: ['Tuesday', 'Thursday', 'Saturday'],
    is_active: true,
    is_approved: true,
    is_demo_profile: true,
    rating: 4.9,
    review_count: 95,
    languages: ['English', 'Urdu', 'Sindhi'],
    education: 'MBBS (DMC), FCPS (Obs & Gynae), MRCOG',
    qualifications: 'MBBS, FCPS Obstetrics & Gynecology, UK Board Certified',
    next_available_slot: 'Tomorrow, 12:00 PM',
    profile: {
      id: 'p-doc-hira',
      role: 'doctor',
      full_name: 'Dr. Hira Shah, FCPS',
      email: 'dr.hira.shah@careflow.ai',
      avatar_url: 'https://images.unsplash.com/photo-1551836022-d5d88e9218df?w=150&auto=format&fit=crop&q=80',
    },
    hospital: INITIAL_HOSPITALS[4],
  },
  {
    id: 'doc-opht-1',
    profile_id: null,
    hospital_id: 'hosp-mayo-lhr',
    specialty: 'Ophthalmology',
    bio: 'Ophthalmic surgeon specializing in refractive laser consultations, cataract diagnostics, and dry eye relief.',
    experience_years: 14,
    consultation_fee: 160,
    consultation_fee_pkr: 2500,
    available_days: ['Monday', 'Tuesday', 'Wednesday', 'Friday'],
    is_active: true,
    is_approved: true,
    is_demo_profile: true,
    rating: 4.8,
    review_count: 72,
    languages: ['English', 'Urdu'],
    education: 'MBBS, FCPS (Ophth), ICO',
    qualifications: 'MBBS, FCPS Ophthalmology, International Council of Ophthalmology',
    next_available_slot: 'Friday, 10:00 AM',
    profile: {
      id: 'p-doc-asad-opht',
      role: 'doctor',
      full_name: 'Dr. Asad Ullah, FCPS',
      email: 'dr.asad.ullah@careflow.ai',
      avatar_url: 'https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?w=150&auto=format&fit=crop&q=80',
    },
    hospital: INITIAL_HOSPITALS[5],
  },
  {
    id: 'doc-dent-1',
    profile_id: null,
    hospital_id: 'hosp-pims-isb',
    specialty: 'Dentistry',
    bio: 'Consultant dental surgeon addressing acute toothaches, crown restorations, root canal treatments, and teeth cleaning.',
    experience_years: 11,
    consultation_fee: 120,
    consultation_fee_pkr: 2000,
    available_days: ['Monday', 'Tuesday', 'Thursday', 'Saturday'],
    is_active: true,
    is_approved: true,
    is_demo_profile: true,
    rating: 4.9,
    review_count: 83,
    languages: ['English', 'Urdu', 'Pashto'],
    education: 'BDS, RDS, C-Implants',
    qualifications: 'Bachelor of Dental Surgery, Certified Implantologist',
    next_available_slot: 'Saturday, 11:30 AM',
    profile: {
      id: 'p-doc-bilal',
      role: 'doctor',
      full_name: 'Dr. Bilal Khan, BDS, RDS',
      email: 'dr.bilal.khan@careflow.ai',
      avatar_url: 'https://images.unsplash.com/photo-1537368910025-700350fe46c7?w=150&auto=format&fit=crop&q=80',
    },
    hospital: INITIAL_HOSPITALS[6],
  },
  {
    id: 'doc-ent-1',
    profile_id: null,
    hospital_id: 'hosp-mayo-lhr',
    specialty: 'ENT (Ear, Nose & Throat)',
    bio: 'ENT expert managing chronic allergic rhinitis, tonsil discomfort, auditory vertigo, and sinus endoscopic screenings.',
    experience_years: 15,
    consultation_fee: 145,
    consultation_fee_pkr: 2600,
    available_days: ['Wednesday', 'Thursday', 'Friday'],
    is_active: true,
    is_approved: true,
    is_demo_profile: true,
    rating: 4.8,
    review_count: 91,
    languages: ['English', 'Urdu'],
    education: 'MBBS, FCPS (Oto-Rhino-Laryngology)',
    qualifications: 'MBBS, FCPS Otolaryngology',
    next_available_slot: 'Thursday, 11:00 AM',
    profile: {
      id: 'p-doc-mansoor',
      role: 'doctor',
      full_name: 'Dr. Tariq Al-Mansoor, FCPS',
      email: 'dr.tariq.mansoor@careflow.ai',
      avatar_url: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&auto=format&fit=crop&q=80',
    },
    hospital: INITIAL_HOSPITALS[5],
  },
  {
    id: 'doc-pulm-1',
    profile_id: null,
    hospital_id: 'hosp-akuh-khi',
    specialty: 'Pulmonology',
    bio: 'Senior pulmonologist addressing adult asthma, chronic coughing, seasonal bronchospasms, and lung function assessments.',
    experience_years: 16,
    consultation_fee: 175,
    consultation_fee_pkr: 3000,
    available_days: ['Monday', 'Wednesday', 'Friday'],
    is_active: true,
    is_approved: true,
    is_demo_profile: true,
    rating: 4.9,
    review_count: 104,
    languages: ['English', 'Urdu', 'Sindhi'],
    education: 'MBBS (AKU), MRCP (UK), FCCP (USA)',
    qualifications: 'MBBS, MRCP UK, Fellow American College of Chest Physicians',
    next_available_slot: 'Today, 04:30 PM',
    profile: {
      id: 'p-doc-bilawal',
      role: 'doctor',
      full_name: 'Dr. Bilawal Sheikh, MRCP',
      email: 'dr.bilawal.sheikh@careflow.ai',
      avatar_url: 'https://images.unsplash.com/photo-1582750433449-648ed127bb54?w=150&auto=format&fit=crop&q=80',
    },
    hospital: INITIAL_HOSPITALS[2],
  },
  {
    id: 'doc-gastro-1',
    profile_id: null,
    hospital_id: 'hosp-services-lhr',
    specialty: 'Gastroenterology',
    bio: 'Clinical gastroenterologist treating chronic acid reflux (GERD), gastritis, irritable bowel syndromes, and digestive pain.',
    experience_years: 17,
    consultation_fee: 195,
    consultation_fee_pkr: 3200,
    available_days: ['Tuesday', 'Thursday', 'Saturday'],
    is_active: true,
    is_approved: true,
    is_demo_profile: true,
    rating: 4.9,
    review_count: 112,
    languages: ['English', 'Urdu'],
    education: 'MBBS (KE), FCPS (Gastroenterology)',
    qualifications: 'MBBS, FCPS Gastroenterology, Therapeutic Endoscopist',
    next_available_slot: 'Saturday, 10:30 AM',
    profile: {
      id: 'p-doc-farhan',
      role: 'doctor',
      full_name: 'Dr. Farhan Qureshi, FCPS',
      email: 'dr.farhan.qureshi@careflow.ai',
      avatar_url: 'https://images.unsplash.com/photo-1622253692010-333f2da6031d?w=150&auto=format&fit=crop&q=80',
    },
    hospital: INITIAL_HOSPITALS[4],
  },
  {
    id: 'doc-cardio-jenkins',
    profile_id: null,
    hospital_id: 'hosp-shifa-isb',
    specialty: 'Cardiology',
    bio: 'Visiting Senior Cardiologist specializing in preventive heart disease, rhythm analysis, and cardiovascular research trials.',
    experience_years: 15,
    consultation_fee: 180,
    consultation_fee_pkr: 3500,
    available_days: ['Monday', 'Tuesday', 'Wednesday'],
    is_active: true,
    is_approved: true,
    is_demo_profile: true,
    rating: 4.9,
    review_count: 78,
    languages: ['English', 'Urdu'],
    education: 'MD, FACC, Consultant Cardiologist',
    qualifications: 'MD, Fellow American College of Cardiology',
    next_available_slot: 'Today, 03:00 PM',
    profile: {
      id: 'p-doc-jenkins-visiting',
      role: 'doctor',
      full_name: 'Dr. Sarah Farooq, FCPS',
      email: 'dr.sarah.farooq@careflow.ai',
      avatar_url: 'https://images.unsplash.com/photo-1559839734-2b71ea197ec2?w=150&auto=format&fit=crop&q=80',
    },
    hospital: INITIAL_HOSPITALS[0],
  },
  {
    id: 'doc-ric-cardio-1',
    profile_id: 'p-doc-ric-1',
    hospital_id: 'hosp-ric-rwp',
    specialty: 'Cardiology',
    bio: 'Consultant Interventional Cardiologist at Rawalpindi Institute of Cardiology specializing in primary PCI angioplasty, hypertension, and preventive cardiac wellness.',
    experience_years: 15,
    consultation_fee: 150,
    consultation_fee_pkr: 2500,
    available_days: ['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday'],
    is_active: true,
    is_approved: true,
    is_demo_profile: true,
    rating: 4.9,
    review_count: 112,
    languages: ['English', 'Urdu', 'Potohari'],
    education: 'MBBS (RMC), FCPS (Cardiology)',
    qualifications: 'MBBS, FCPS Cardiology, Member Pakistan Cardiac Society',
    next_available_slot: 'Today, 04:30 PM',
    profile: {
      id: 'p-doc-ric-1',
      role: 'doctor',
      full_name: 'Dr. Tariq Mahmood, FCPS',
      email: 'dr.tariq.mahmood@careflow.ai',
      avatar_url: 'https://images.unsplash.com/photo-1537368910025-700350fe46c7?w=150&auto=format&fit=crop&q=80',
    },
    hospital: INITIAL_HOSPITALS[8],
  },
  // Pending Approval Doctors (For Admin Verification Workflow)
  {
    id: 'doc-pending-1',
    profile_id: 'p-doc-pending-1',
    hospital_id: 'hosp-skmch-lhr',
    specialty: 'Neurology',
    bio: 'Fellow in Neurological Sciences focusing on clinical neuro-diagnostics, neuropathies, and migraine management protocols.',
    experience_years: 7,
    consultation_fee: 140,
    available_days: ['Monday', 'Wednesday'],
    is_active: true,
    is_approved: false,
    rating: 4.7,
    review_count: 32,
    languages: ['English', 'Urdu'],
    education: 'MBBS, FCPS Neurology (Pending Verification)',
    profile: {
      id: 'p-doc-pending-1',
      role: 'doctor',
      full_name: 'Dr. Asad Qureshi, FCPS',
      email: 'dr.asad.qureshi@careflow.ai',
      avatar_url: 'https://images.unsplash.com/photo-1622253692010-333f2da6031d?w=150&auto=format&fit=crop&q=80',
    },
    hospital: INITIAL_HOSPITALS[0],
  },
  {
    id: 'doc-pending-2',
    profile_id: 'p-doc-pending-2',
    hospital_id: 'hosp-isb-1',
    specialty: 'Pediatrics',
    bio: 'Pediatric care consultant with clinical focus on neonatology, infant respiratory health, and growth checkups.',
    experience_years: 5,
    consultation_fee: 110,
    available_days: ['Tuesday', 'Thursday'],
    is_active: true,
    is_approved: false,
    rating: 4.8,
    review_count: 24,
    languages: ['English', 'Urdu'],
    education: 'MBBS, DCH, MCPS (Pending Verification)',
    profile: {
      id: 'p-doc-pending-2',
      role: 'doctor',
      full_name: 'Dr. Ayesha Malik, DCH',
      email: 'dr.ayesha.malik@careflow.ai',
      avatar_url: 'https://images.unsplash.com/photo-1594824813684-25e6ffc6b541?w=150&auto=format&fit=crop&q=80',
    },
    hospital: INITIAL_HOSPITALS[2],
  }
];

// Helper to format ISO date strings for today and tomorrow
export const getTodayDateString = (): string => {
  const d = new Date();
  return d.toISOString().split('T')[0];
};

export const getTomorrowDateString = (): string => {
  const d = new Date();
  d.setDate(d.getDate() + 1);
  return d.toISOString().split('T')[0];
};

export const getFutureDateString = (offsetDays: number): string => {
  const d = new Date();
  d.setDate(d.getDate() + offsetDays);
  return d.toISOString().split('T')[0];
};

// Generate standard slot timings
export const STANDARD_TIME_SLOTS = [
  { start: '09:00:00', end: '09:30:00', label: '09:00 AM' },
  { start: '09:30:00', end: '10:00:00', label: '09:30 AM' },
  { start: '10:00:00', end: '10:30:00', label: '10:00 AM' },
  { start: '10:30:00', end: '11:00:00', label: '10:30 AM' },
  { start: '11:00:00', end: '11:30:00', label: '11:00 AM' },
  { start: '11:30:00', end: '12:00:00', label: '11:30 AM' },
  { start: '14:00:00', end: '14:30:00', label: '02:00 PM' },
  { start: '14:30:00', end: '15:00:00', label: '02:30 PM' },
  { start: '15:00:00', end: '15:30:00', label: '03:00 PM' },
  { start: '15:30:00', end: '16:00:00', label: '03:30 PM' },
  { start: '16:00:00', end: '16:30:00', label: '04:00 PM' },
];

export const INITIAL_APPOINTMENTS: Appointment[] = [
  {
    id: 'apt11111-1111-1111-1111-111111111111',
    patient_id: DEMO_PROFILES.patient.id,
    doctor_id: INITIAL_DOCTORS[0].id,
    department_id: INITIAL_DEPARTMENTS[0].id,
    hospital_id: INITIAL_HOSPITALS[0].id,
    appointment_date: getTodayDateString(),
    start_time: '11:00:00',
    end_time: '11:30:00',
    status: 'confirmed',
    reason: 'Follow-up consultation for mild hypertension and routine ECG review.',
    notes: 'Please bring recent blood pressure log and medication history.',
    patient: DEMO_PROFILES.patient,
    doctor: INITIAL_DOCTORS[0],
    department: INITIAL_DEPARTMENTS[0],
    hospital: INITIAL_HOSPITALS[0],
    created_at: new Date().toISOString(),
  },
  {
    id: 'apt22222-2222-2222-2222-222222222222',
    patient_id: DEMO_PROFILES.patient.id,
    doctor_id: INITIAL_DOCTORS[1].id,
    department_id: INITIAL_DEPARTMENTS[1].id,
    hospital_id: INITIAL_HOSPITALS[0].id,
    appointment_date: getTomorrowDateString(),
    start_time: '10:30:00',
    end_time: '11:00:00',
    status: 'confirmed',
    reason: 'Annual skin mole inspection and dry patch checkup.',
    notes: 'Outpatient clinic room 302.',
    patient: DEMO_PROFILES.patient,
    doctor: INITIAL_DOCTORS[1],
    department: INITIAL_DEPARTMENTS[1],
    hospital: INITIAL_HOSPITALS[0],
    created_at: new Date().toISOString(),
  }
];

export const INITIAL_QUEUES: Queue[] = [
  {
    id: 'q1111111-1111-1111-1111-111111111111',
    appointment_id: 'apt11111-1111-1111-1111-111111111111',
    queue_date: getTodayDateString(),
    position: 3,
    patients_ahead: 2,
    estimated_wait_minutes: 20,
    status: 'waiting',
    appointment: INITIAL_APPOINTMENTS[0],
    updated_at: new Date().toISOString(),
  }
];

export const INITIAL_DOCUMENTS: MedicalDocument[] = [
  {
    id: 'doc-rep-1111',
    patient_id: DEMO_PROFILES.patient.id,
    appointment_id: 'apt11111-1111-1111-1111-111111111111',
    document_name: 'Complete_Blood_Count_Panel_Report.pdf',
    document_type: 'Blood Test',
    storage_path: 'reports/cbc_panel_2026.pdf',
    file_size: 245760,
    mime_type: 'application/pdf',
    document_date: getFutureDateString(-7),
    created_at: new Date(Date.now() - 7 * 86400000).toISOString(),
  },
  {
    id: 'doc-rep-2222',
    patient_id: DEMO_PROFILES.patient.id,
    appointment_id: 'apt11111-1111-1111-1111-111111111111',
    document_name: 'Echocardiogram_Doppler_Summary.pdf',
    document_type: 'Ultrasound',
    storage_path: 'reports/echo_summary_2026.pdf',
    file_size: 489200,
    mime_type: 'application/pdf',
    document_date: getFutureDateString(-30),
    created_at: new Date(Date.now() - 30 * 86400000).toISOString(),
  }
];

export const INITIAL_NOTIFICATIONS: AppNotification[] = [
  {
    id: 'notif-111',
    user_id: DEMO_PROFILES.patient.id,
    type: 'booking_confirmed',
    title: 'Appointment Confirmed',
    message: 'Your visit with Dr. Sarah Farooq (Cardiology) is confirmed for today at 11:00 AM.',
    is_read: false,
    related_appointment_id: 'apt11111-1111-1111-1111-111111111111',
    created_at: new Date(Date.now() - 3600000).toISOString(),
  },
  {
    id: 'notif-222',
    user_id: DEMO_PROFILES.patient.id,
    type: 'queue_update',
    title: 'Live Queue Position #3',
    message: 'You are 3rd in line with Dr. Sarah Farooq. Estimated wait time is approximately 20 minutes.',
    is_read: false,
    related_appointment_id: 'apt11111-1111-1111-1111-111111111111',
    created_at: new Date(Date.now() - 1800000).toISOString(),
  }
];

export const INITIAL_SAVED_DOCTORS: SavedDoctor[] = [
  {
    id: 'save-1',
    patient_id: DEMO_PROFILES.patient.id,
    doctor_id: 'doc-cardio-1',
    doctor: INITIAL_DOCTORS[0],
    created_at: new Date(Date.now() - 5 * 86400000).toISOString(),
  },
  {
    id: 'save-2',
    patient_id: DEMO_PROFILES.patient.id,
    doctor_id: 'doc-derma-1',
    doctor: INITIAL_DOCTORS[1],
    created_at: new Date(Date.now() - 2 * 86400000).toISOString(),
  }
];

// ==============================================================================
// 10. FAMILY PROFILES
// ==============================================================================
export const INITIAL_FAMILY_MEMBERS: FamilyMember[] = [
  {
    id: 'fam-child-1',
    patient_id: DEMO_PROFILES.patient.id,
    full_name: 'Ali Khan',
    relationship: 'Child',
    date_of_birth: '2018-06-12',
    gender: 'Male',
    blood_group: 'O+',
    allergies: ['Penicillin', 'Peanuts'],
    notes: 'Up to date with pediatric vaccinations. Mild seasonal dust sensitivity.',
    created_at: new Date(Date.now() - 30 * 86400000).toISOString(),
  },
  {
    id: 'fam-mother-2',
    patient_id: DEMO_PROFILES.patient.id,
    full_name: 'Fatima Begum',
    relationship: 'Mother',
    date_of_birth: '1959-11-20',
    gender: 'Female',
    blood_group: 'B+',
    allergies: ['Sulfa drugs'],
    notes: 'Managed Type 2 Diabetes and borderline hypertension. Monitored biannually.',
    created_at: new Date(Date.now() - 45 * 86400000).toISOString(),
  },
  {
    id: 'fam-spouse-3',
    patient_id: DEMO_PROFILES.patient.id,
    full_name: 'Amina Ahmed Khan',
    relationship: 'Spouse',
    date_of_birth: '1992-04-18',
    gender: 'Female',
    blood_group: 'A+',
    allergies: [],
    notes: 'No known chronic conditions. Routine annual health checks.',
    created_at: new Date(Date.now() - 60 * 86400000).toISOString(),
  }
];

// ==============================================================================
// 11. DIGITAL CLINICAL PRESCRIPTIONS
// ==============================================================================
export const INITIAL_PRESCRIPTIONS: Prescription[] = [
  {
    id: 'rx-cardio-101',
    appointment_id: 'apt22222-2222-2222-2222-222222222222',
    doctor_id: 'doc-cardio-1',
    patient_id: DEMO_PROFILES.patient.id,
    prescription_date: getFutureDateString(-14),
    clinical_diagnosis_notes: 'Primary Essential Hypertension (Grade 1) with mild exertional sinus tachycardia. Cardiovascular examination normal. Advised lifestyle modifications, low sodium diet (<2g/day) and 30 min daily brisk walks.',
    medicines: [
      {
        medicine_name: 'Amlodipine Besylate',
        dosage: '5 mg',
        frequency: 'Once daily (Morning)',
        duration: '30 Days',
        instructions: 'Take after breakfast with water. Avoid grapefruit juice.'
      },
      {
        medicine_name: 'Nebivolol HCl',
        dosage: '2.5 mg',
        frequency: 'Once daily (Morning)',
        duration: '30 Days',
        instructions: 'Monitor resting pulse rate weekly; aim for 65-75 bpm.'
      },
      {
        medicine_name: 'Rosuvastatin Calcium',
        dosage: '10 mg',
        frequency: 'Once daily (Night)',
        duration: '30 Days',
        instructions: 'Take at bedtime for lipid panel stabilization.'
      }
    ],
    follow_up_date: getFutureDateString(16),
    follow_up_instructions: 'Repeat fasting lipid panel and fasting blood sugar before next review. Bring home BP log.',
    doctor: INITIAL_DOCTORS[0],
    created_at: new Date(Date.now() - 14 * 86400000).toISOString(),
  }
];

// ==============================================================================
// 12. VERIFIED DOCTOR REVIEWS
// ==============================================================================
export const INITIAL_REVIEWS: DoctorReview[] = [
  {
    id: 'rev-1',
    doctor_id: 'doc-cardio-1',
    patient_id: DEMO_PROFILES.patient.id,
    appointment_id: 'apt22222-2222-2222-2222-222222222222',
    rating: 5,
    patient_name: 'Ahmed Khan',
    comment: 'Dr. Sarah Farooq is exceptionally attentive and compassionate. She explained the Doppler echocardiogram in simple terms, adjusted my medication smoothly, and gave great dietary advice.',
    created_at: new Date(Date.now() - 12 * 86400000).toISOString(),
  },
  {
    id: 'rev-2',
    doctor_id: 'doc-ortho-1',
    patient_id: 'p0000000-0000-0000-0000-000000000099',
    appointment_id: 'apt-prev-ortho-99',
    rating: 5,
    patient_name: 'Zainab Malik',
    comment: 'Outstanding orthopedic assessment for my lumbar spine pain. The physical therapy regimen and ergonomic workspace suggestions improved my posture within one week.',
    created_at: new Date(Date.now() - 8 * 86400000).toISOString(),
  },
  {
    id: 'rev-3',
    doctor_id: 'doc-peds-1',
    patient_id: 'p0000000-0000-0000-0000-000000000098',
    appointment_id: 'apt-prev-peds-98',
    rating: 5,
    patient_name: 'Bilal Hussain',
    comment: 'Dr. Ayesha has a wonderfully calm bedside manner with young children. Our toddler was calm throughout the checkup and vaccination.',
    created_at: new Date(Date.now() - 4 * 86400000).toISOString(),
  }
];

// ==============================================================================
// 13. HEALTH JOURNEY TIMELINE
// ==============================================================================
export const INITIAL_TIMELINE_EVENTS: HealthTimelineEvent[] = [
  {
    id: 'tle-1',
    patient_id: DEMO_PROFILES.patient.id,
    date: getFutureDateString(-14),
    type: 'visit_completed',
    title: 'Cardiology Consultation Completed',
    description: 'Comprehensive cardiovascular assessment with Dr. Sarah Farooq at CareFlow Medical Center.',
    reference_id: 'apt22222-2222-2222-2222-222222222222',
    doctor_name: 'Dr. Sarah Farooq',
    hospital_name: 'CareFlow Medical Center',
    badge_label: 'Completed Visit',
    created_at: new Date(Date.now() - 14 * 86400000).toISOString(),
  },
  {
    id: 'tle-2',
    patient_id: DEMO_PROFILES.patient.id,
    date: getFutureDateString(-14),
    type: 'prescription_issued',
    title: 'Digital Prescription Issued',
    description: '3 medications prescribed (Amlodipine, Nebivolol, Rosuvastatin) for hypertension management.',
    reference_id: 'rx-cardio-101',
    doctor_name: 'Dr. Sarah Farooq',
    hospital_name: 'CareFlow Medical Center',
    badge_label: 'Rx Issued',
    created_at: new Date(Date.now() - 14 * 86400000).toISOString(),
  },
  {
    id: 'tle-3',
    patient_id: DEMO_PROFILES.patient.id,
    date: getFutureDateString(-7),
    type: 'report_uploaded',
    title: 'Complete Blood Count Panel Uploaded',
    description: 'Diagnostic laboratory results uploaded to secure patient documents vault.',
    reference_id: 'doc-rep-1111',
    hospital_name: 'CareFlow Clinical Diagnostics',
    badge_label: 'Lab Report',
    created_at: new Date(Date.now() - 7 * 86400000).toISOString(),
  },
  {
    id: 'tle-4',
    patient_id: DEMO_PROFILES.patient.id,
    date: getFutureDateString(0),
    type: 'appointment_booked',
    title: 'Cardiology Checkup Scheduled',
    description: 'Follow-up appointment with Dr. Sarah Farooq at CareFlow Medical Center.',
    reference_id: 'apt11111-1111-1111-1111-111111111111',
    doctor_name: 'Dr. Sarah Farooq',
    hospital_name: 'CareFlow Medical Center',
    badge_label: 'Scheduled Visit',
    created_at: new Date(Date.now() - 1 * 86400000).toISOString(),
  }
];

// ==============================================================================
// 14. CARE PASSPORT INITIAL DATA
// ==============================================================================
export const INITIAL_PASSPORT: CarePassport = {
  id: 'pass-alex-01',
  patient_id: DEMO_PROFILES.patient.id,
  cnic: '35202-4819203-1',
  blood_group: 'B+',
  emergency_contact_name: 'Tariq Hayes',
  emergency_contact_phone: '+92 (300) 412-9843',
  allergies: ['Penicillin', 'Sulfa Antibiotics'],
  chronic_conditions: ['Mild Hypertension', 'Seasonal Allergic Rhinitis'],
  current_medications: ['Amlodipine 5mg Daily', 'Cetirizine 10mg PRN'],
  privacy_settings: {
    share_timeline: true,
    share_prescriptions: true,
    share_reports: true,
    share_allergies: true,
    share_conditions: true,
    allow_doctor_briefing: true
  },
  created_at: '2026-01-10T10:00:00Z',
  updated_at: '2026-03-01T12:30:00Z'
};

